### ISSUE TITLE
Satellite Terminal Inventory Bug

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#202]
* **Modpack Version**: 1.2.1.
* **Issue**: When opening a (connected) Satellite Terminal the contents of the player's inventory seem to disappear while only Data Storage Units remain visible and the inventory get (visually) filled up with more and more "fale" Satellite ID Chips the more Terminals you open.
The visual bug resets when clicking an inventory slot that has an actual (invisible) item in it.

This is very noticeable when collecting Data Storage Units from multiple Terminals.

E: This behavior has now shifted and I can only see Satellite ID Chips. This has effectively broken my Satellite Terminals and they are not usable any more. A quick relog has not helped. I can see if I can fix my progression in some other fashion.

E2: Must be a server thing since only breaking the blocks would fix the issue.

**Comment by aaronhowser1** [comment]
Satellite Terminals are probably the buggiest part about Advanced Rocketry. I suggest submitting this to the [AR Issue Tracker ](https://github.com/zmaster587/AdvancedRocketry/issues)as well though

**Comment by tfox83** [comment]
fixed in 1.4.0

**Comment by TrademarkTM** [comment]
I am still having this issue on 1.4.1 in a LAN server.
The inventory gets completely messed up, the warp core doesn't work properly (doesn't recognize dilithium when your inventory is glitched). Sometimes the items are also deleted.. it made me lose 2 satellites.

Hope this can be fixed soon.
Thanks.

**Comment by dantheman4700** [comment]
still having this issue
