### ISSUE TITLE
Held items get deleted when placing multiple torches

### ISSUE THREAD

**Issue by sandrofigo** [FTBTeam/FTB-Continuum#212]
* **Modpack Version**: 1.2.1 and above

* **Issue**: Equip two (2) torches in the left hand and any tool/item/block that allows you to place the torches from the left hand with a right-click. Place the torches in a corner so they merge. The item in the selected slot will vanish without a trace.

* **Link to Log or Crash File Paste**: No errors/warnings/info in the log file

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Forge MultiPart CBE

* **Known Fix**: None

![screenshot_1](https://user-images.githubusercontent.com/2115149/41408045-aefbee72-6fd1-11e8-8477-4ced10e6ac47.png)

**Comment by sandrofigo** [comment]
Recording that shows the misbehavior:
![export](https://user-images.githubusercontent.com/2115149/41407837-f0fbf534-6fd0-11e8-8fcc-2e3d115c5e36.gif)

**Comment by alexsch01** [comment]
middle click seems to fix it, right?

**Comment by sandrofigo** [comment]
Middle-click has no effect.

**Comment by tfox83** [comment]
Fixed in 1.4.0

**Comment by sandrofigo** [comment]
@tfox83 Just updated to 1.4.0 and the problem still persists.

**Comment by tfox83** [comment]
weird this issue didnt happen in my old dev world but happens in a new world.  Ill get this submitted

**Comment by tfox83** [comment]
closed due to no fix from dev
