### ISSUE TITLE
Smart Wrench does not work on Thermal Suite blocks

### ISSUE THREAD

**Issue by Morganamilo** [FTBTeam/FTB-Continuum#278]
* **Modpack Version**: 1.3.1

* **Issue**: The itemducts, fluiducts and fluxducts quests should specifically mention which wrench to use. The former two do mention to use a "wrench" but there are about a thousand different wrenching when it comes to FTB.
The wiki shows the crescent hammer as being the the preferred tool, but after testing the AE2 wrenches and flux infused battle/omni wrench also work. You also could add a quest where you are required to make a wrench.

**Comment by aaronhowser1** [comment]
The first Powercell quest requires a Smart Wrench from RFTools, which works I think.

**Comment by Morganamilo** [comment]
Nope, smart wrench does not work on ducts.

**Comment by aaronhowser1** [comment]
I'll make an issue on the RFTools issue tracker then, it worked back in testing before a major Thermal Suite update.

**Comment by aaronhowser1** [comment]
Made an issue: McJtyMods/RFTools/issues/1800

**Comment by tfox83** [comment]
Fixed in 1.4.0

**Comment by aaronhowser1** [comment]
No it wasn't, the Smart Wrench still doesn't work on Thermal Suite blocks. I just tried to pick up a Portable Tank with it in wrench mode and it didn't pick it up.

**Comment by tfox83** [comment]
Sorry was testing with the wrong wench, you are right it does not work.  I will mark this as submitted, but based on the amount of open tickets he has I wouldn't expect a fix anytime soon.

**Comment by tfox83** [comment]
closing due to no fix
