### ISSUE TITLE
Downgrade MineTogether to remove paid minigames and restore refresh button

### ISSUE THREAD

**Issue by HDR** [FTBTeam/FTB-Continuum#357]
* **Modpack Version**: 1.4.1

* **Issue**: The new version of MineTogether replaces the "Refresh" tab with a new "minigames" tab, making it easy to accidentally hit said button (The refresh button was relocated), the new minigames tab has paid Minigames, that you need "CreeperHost" credits to play, it seems like this was intended to make people click minigames instead of refreshing, and it's a stupid attempt from creeperhost to make money, this should not be in a minecraft pack that young children play.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: MineTogether

* **Known Fix**: Downgrade MineTogether

**Comment by kristi71111** [comment]
Honestly this move is downright annoying what you're doing here is updating a mod that basically replaces the most used button on the multiplayer menu with a minigames button that requires you to use "creeper host" credits to play said minigames.

This mod should be downgraded to the version that was used in FTB Continuum 1.3.0. Also to add to what @MrHDR stated this mod basically tricks players to click the minigames button and then requires them to either have some credits on their creeperhost account or buy them? I mean you get 5 credits for free but isn't the mod kinda tricking people into doing micro trascations?

**Comment by tfox83** [comment]
Fixed in 1.5.0 with newer version of MT

**Comment by HDR** [comment]
It's still the same for newer versions of minetogether, updating it does not do anything.
