### ISSUE TITLE
Unable to configure RFTools storage tablet.

### ISSUE THREAD

**Issue by Jimmy469** [FTBTeam/FTB-Continuum#49]
* **Modpack Version**: 1.0.2

* **Issue**: The recepies to configure the RFTools storage tablet have been removed (such as Tablet + Storage Module Tier (X), or Tablet + Storage Screen), thus making it impossible to put a module into the tablet.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: RFTools

* **Known Fix**: rftools.zs line 16'ish: recipes.remove(<rftools:storage_module_tablet>); removes the recepies that configure the tablet, in addition to the one that removes the make the base tablet. Should do something like .removeShaped(<DefaultRecepie>,<rftools:storage_module_tablet>);

**Comment by tfox83** [comment]
fixed in dev

**Comment by VT-14** [comment]
Unfortunately, this issue still persists in Version 1.1.0.

After an hour or so of research (this is my first time messing with CraftTweaker), I believe the correct recipe removal for line 17 is:

`recipes.remove(<rftools:storage_module_tablet>, true);`

The true indicates that the removed recipe must match the NBT of the specified item.  The specified item has no NBT, so that only removes the recipe for the blank tablet while leaving all of the module install/uninstall recipes intact.

`removeShaped` didn't work because all of the module installation recipes are shaped.

I have applied this to my Server and Client and it appears to be working.  Here are the reported recipes in JEI:
https://imgur.com/a/pVftVpe
